# a markdown rendering test
in which we try to get files with the .mmd extension rendered as markdown

## what is the verdict?
I'm not holding my breath.

## adding another line
perhaps the format is checked only when there are modifications made?

<!-- adding vim header will help setting syntax automatically, but will it help github? -->
<!-- vim: syntax=Markdown -->
